packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/legend'
  - 'packages/attribute-popup'
  - 'packages/search'
  - 'packages/export'
  - 'packages/share'
  - 'packages/*'